### ISSUE TITLE
Fading the explosion

### ISSUE THREAD

**Issue by andreysamode** [blackmiaool/jquery-image-explode#3]
The explosion looks great. Thanks for such a tiny awesome plugin.

How can I reference the newly created "explode-wrapper" element, so I can fade it out as the image explodes and do other things to it (like remove it at the end)? I'd like to have a bunch of explosions, so I need to clear up the canvas elements and remove them.

Thanks!

**Comment by blackmiaool** [comment]
You can't.
Try the "release" and "fadeTime" parameters in this page: https://blackmiaool.com/jquery-image-explode/playground.html
If they can't meet your demand, try to read the code.

**Comment by blackmiaool** [comment]
```javascript
$target.explode({
                    maxWidth: 15,
                    minWidth: 5,
                    radius: 231,
                    release: false,
                    recycle: false,
                    explodeTime: 320,
                    canvas: true,
                    round: false,
                    maxAngle: 360,
                    gravity: 10,
                    groundDistance: 150,
                });
console.log($target.prop("explode-wrapper"))// the wrapper

**Comment by andreysamode** [comment]
Perfect! Exploding unicorns thank you :-)
